name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: transcript-orchestration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run audit
      - run: npm test
        env:
          AWS_REGION: "eu-west-1"
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-node-18
          parallel: true
          path-to-lcov: transcript-orchestration/coverage/lcov.info
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
          path-to-lcov: transcript-orchestration/coverage/lcov.info
